apiVersion: v1
kind: PersistentVolume
metadata:
  name: mean-volume
  labels:
    relapp: mean
spec:
  capacity:
     storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
     path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mean-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 300M
  selector:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mean-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 300M
  selector:
     matchLabels:
      relapp: mean
     matchLabels:
      relapp: mean  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mean-pvc3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 300M
  selector:
     matchLabels:
      relapp: mean

